# @package hydra.job_logging
# python logging configuration for tasks
version: 1
formatters:
  simple:
    format: '[%(asctime)s CST][%(levelname)s][global_r${oc.env:RANK,0}] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  colorlog:
    '()': 'colorlog.ColoredFormatter'
    format: '[%(cyan)s%(asctime)s CST%(reset)s][%(blue)sglobal_r${oc.env:RANK,0}%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
    log_colors:
      DEBUG: purple
      INFO: green
      WARNING: yellow
      ERROR: red
      CRITICAL: red
handlers:
  console:
    class: logging.StreamHandler
    formatter: colorlog
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    # absolute file path
    filename: ${hydra.runtime.output_dir}/train-${now:%Y-%m-%d_%H-%M-%S}-global_rank${oc.env:RANK,0}.log
    mode: w
root:
  level: INFO
  handlers: [console, file]

disable_existing_loggers: false